captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 2910562670@qq.com
    nickname: C博
    secret: hjxcyzobayfkdddj
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 39f4e9cc4974d9a5421e0cb1f8a83ced
jwt:
    access_token_secret: OrADW_K1kZVbOlg3DxmFBnzSeoGfB3lrJSDTdIeSDcc=
    refresh_token_secret: 80KRWuQIL0bpdYKAN5Fs-xmodSQvO1oZlqDzyHUMjR4=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    username: root
    password: "123456"
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z0
    bucket: xxx
    img_path: https://xxx.xxx/
    access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    use_https: true
    use_cdn_domains: true
qq:
    enable: false
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://xxx.xxx/xxx
redis:
    address: 127.0.0.1:6379
    password: ""
    db: 0
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: 8HY5gW04Nu11C4AknpejLG9Svdp_3TVHUhiJNccT5qM=
    oss_type: local
upload:
    size: 20
    path: uploads
website:
    logo: /uploads/image/96d6f2e7e1f705ab5e59c84a6dc009b2-20250518155549.png
    full_logo: /uploads/image/96d6f2e7e1f705ab5e59c84a6dc009b2-20250518155549.png
    title: Cbo的个人博客
    slogan: 博客标题
    slogan_en: Blog Title
    description: 博客描述
    version: 1.0.0
    created_at: "2025-1-15"
    icp_filing: icp备案号
    public_security_filing: 公安备案号
    bilibili_url: https://space.bilibili.com/1843665576?spm_id_from=333.1007.0.0
    gitee_url: https://gitee.com/C-_bo/projects
    github_url: https://github.com/Cboyyds?tab=repositories
    name: 程乂
    job: goland开发程序员
    address: 河南省新乡市平原体育中心
    email: 2910562670@qq.com
    qq_image: /uploads/image/583fbaee2446441e8197a420c11aa77b-20250520105042.png
    wechat_image: /uploads/image/3969711efff3511bb34291bf4e63bf62-20250520105414.png
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true
